### PR TITLE
add forward and docstrings

### PR DESCRIPTION
**Pull request by hoangbros03**

### CODE REVIEW

**Comment by nbtin** [comment]
Hi guys, I'm glad to be one of your repo's reviewers.
I would like to review the repo depending on 3 aspects: Structure, Ability to execute, and Convention.

**1. Structure:**
- I found that your repo did **not** have a really good structure.
- Suggestion:
     - Try to put some files with the same domain or function into a folder...
     - You guys should have some simple unit tests for your repo. 

**2. Ability to execute:**
- First, you have a **strange** character at the end of the `requirements.txt` file, and people who don't know how to fix it may face some struggle.
- Second, please notice that you guys should have a `README` file, with *at least* a brief instruction to install/execute the library (I had to find a way to execute the program by reading the code file by file :sleepy:).
- However, I couldn't execute the program because of some problems with the libraries. Maybe I ran it the wrong way (wait to see your instructions).

**3. Convention:**
- File names **lack consistency**. For example: `heic_to_png.py` $\neq$ `pdfHandler.py`.
- The source code with clear comments. :heavy_check_mark:
- The variables, classes, and functions were named in an easy-to-read way. Good job! :heavy_check_mark:

*Have a great day,
Tin.*

**Review by lynguyenminh — APPROVED** [review]
That's fantastic. I have no comments or suggestions.

**Review by ngochafromdn — COMMENTED** [review]
* Pros :
 - good idea, comments can explain the idea well (CODE CONVENTION)
* Cons:
- not good structure (STRUCTURE)
- lack consistency (CODE CONVENTION)
- lack of instruction (CODE CONVENTION)  
- lack of unit tests (STRUCTURE)
Suggestion : improve by adding unit tests, fix the structure, add instructions, fix the inconsistent names.

**Comment by phkhanhtrinh23** [comment]
I just have some few comments:

Weak points:
First, there is an unfamiliar character at the end of the requirements.txt file, which could cause difficulties for those unfamiliar with requirement installation. Second, it is important to have a README.md file with clear installation and execution instructions for the library. I had to navigate through the code files to figure out how to run the program.

Strong points:
First, the source code is well-commented. Second, the variables, classes, and functions are named in a clear and readable manner.

Great job after all!

**Review by nbtin — CHANGES_REQUESTED** [review]
Seems like you haven't fixed the problem that I pointed out in the requirements.txt file...

**Comment by hoangbros03** [comment]
Sorry, the weird character was added by "end-of-file-fixer" in pre-commit config. I have deleted the character and disabled this check.

**Comment by hoangbros03** [comment]
> I just have some few comments:
> 
> Weak points: First, there is an unfamiliar character at the end of the requirements.txt file, which could cause difficulties for those unfamiliar with requirement installation. Second, it is important to have a README.md file with clear installation and execution instructions for the library. I had to navigate through the code files to figure out how to run the program.
> 
> Strong points: First, the source code is well-commented. Second, the variables, classes, and functions are named in a clear and readable manner.
> 
> Great job after all!

I added instruction in README.md in lastest commit, feel free to review it :3

**Review by nbtin — APPROVED** [review]

**Review by phkhanhtrinh23 — COMMENTED** [review]
I have reviewed and it is perfectly well-done now!

**Pull request merged**
